services:
  database:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: CST8277
      MYSQL_DATABASE: twitter_db
      MYSQL_USER: twitter_user
      MYSQL_PASSWORD: CST8277
    volumes:
      - database_mysql:/var/lib/mysql

volumes:
  database_mysql:
